### ISSUE TITLE
Bill of Materials (BoM)?

### ISSUE THREAD

**Issue by pdp7** [mike-rankin/BeagleBoneBlack_3.3V_SPI_Oled#1]
Thanks for sharing the design files and gerbers.

Could you please post a bill of materials?

**Comment by mike-rankin** [comment]
It's the page after the schematic.

**Comment by mike-rankin** [comment]
https://github.com/mike-rankin/BeagleBoneBlack_3.3V_SPI_Oled

**Comment by pdp7** [comment]
@mike-rankin Sorry, I am just seeing the Adafruit breakout boards listed on the pages linked from README.md.

Don't I need to buy capacitors, resistors and OLED display to go on the PCB that you designed?

![PCB preview top](https://644db4de3505c40a0444-327723bce298e3ff5813fb42baeefbaa.ssl.cf1.rackcdn.com/91ab3aada253514b65b995e014ef80fe.png)

**Comment by mike-rankin** [comment]
https://github.com/mike-rankin/BeagleBoneBlack_3.3V_SPI_Oled/tree/master/PCB

Has a pdf that shows the schematic and parts list. I may have not made it clear when I posted it today.

**Comment by pdp7** [comment]
@mike-rankin thanks very much for the clarification.  I see it now.  Is there a specific model that you'd recommend on Buy Display?

**Comment by mike-rankin** [comment]
Woah. Nice catch. None of the part number fields are showing. I'll update that in a few hours and let you know.

**Comment by mike-rankin** [comment]
The field on the BOM for part numbers has just been enabled and updated.

Thanks,
Mike

**Comment by pdp7** [comment]
@mike-rankin Thanks!
